kanieckiblog/blog/urls.py
from django.urls import path
from blog.views import register_subscriber, unsubscribe

urlpatterns = [
    path("subscribe/", register_subscriber, name="register_blog_subscriber"),
    path("unsubscribe/", unsubscribe, name="unsubscribe_blog"),
]

kanieckiblog/contact_me/urls.py
from django.urls import path
from .views import contact

urlpatterns = [path("contact", contact, name="ContactMe")]

kanieckiblog/contact_me/models.py
from django.db import models

# Create your models here.


class ContactMessage(models.Model):

    name = models.CharField(max_length=200)

    email = models.EmailField()

    company = models.CharField(max_length=100, null=True, blank=True)

    website = models.URLField(null=True, blank=True)

    message = models.TextField()

kanieckiblog/contact_me/forms.py
from django import forms
from .models import ContactMessage


class ContactMeForm(forms.ModelForm):
    class Meta:
        model = ContactMessage
        fields = ("name", "email", "company", "website", "message")

kanieckiblog/contact_me/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .models import ContactMessage
from .forms import ContactMeForm

# Create your views here.


def contact(request):
    if request.method == "POST":
        form = ContactMeForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(
                request, "Thank you for contacting me! I will get in touch shortly."
            )
    return render(request, "contact_me.html")

kanieckiblog/contact_me/templates/contact_me.html
{% extends "base.html" %}

{% load wagtailcore_tags wagtailimages_tags static %}

{% block body_class %}template-blogpage{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/contact_me_page.css' %}">
{% endblock %}

{% block content %}
<div class="container">
    <h1 class="header">Contact Me</h1>
    <hr style="width: 34%"/>
    <div class="row">
        <div class="contact-me-container">
            <form action="/contact" method="post" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-sm-12 form-group">
                            <input id="id_name" name="name" class="form-control" placeholder="Name" required="true" maxlength="150"/>
                            <div class="invalid-feedback">
                                Please provide a valid name less than 150 characters
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 form-group">
                            <input id="id_email" name="email" type="email" class="form-control" placeholder="Email" required="true"/>
                            <div class="invalid-feedback">
                                Please provide a valid a valid email
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6 col-sm-12 form-group">
                            <input id="id_company" name="company" class="form-control" placeholder="Company" />
                            <div class="invalid-feedback">
                                Please provide a valid company name less than 150 characters
                            </div>
                        </div>
                        <div class="col-md-6 col-sm-12 form-group">
                            <input id="id_website" name="website" class="form-control" placeholder="Website" type="url" />
                            <div class="invalid-feedback">
                                Please provide a valid website url
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <textarea id="id_message" name="message" class="form-control" placeholder="Message" required="true"></textarea>
                            <div class="invalid-feedback">
                                Please provide a comment
                            </div>
                        </div>
                    </div>
                </div>
                <div class="container my-2">
                    <button class="btn" style="width: 100%">Send</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

{% block subscribe %}{% endblock %}